<?php 
###########################################################################
# Copyright Jamit Software 2012, http://www.jamit.com
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
###########################################################################
@set_time_limit(280);

ini_set ('session.gc_maxlifetime', 60*60*4); // 4 hours
require ('../config.php');
require ("admin_common.php");

//ini_set (session.use_trans_sid, false);

JB_admin_header('Admin->Translation / Editing Tool');

$label = array();

$sql = "SELECT * FROM lang WHERE lang_code='".jb_escape_sql($_REQUEST['target_lang'])."' ";
$result = JB_mysql_query ($sql) or die (mysql_error());
$row = mysql_fetch_array($result, MYSQL_ASSOC);

$lang_filename = $row['lang_filename'];
$lang_name = $row['name'];

include (jb_get_english_default_dir()."english_default.php"); // main english default


JBPLUG_append_english_default_labels(); // require the english_defult.php files for the modules
JB_theme_append_english_default_labels();

$source_label = $label; // default english labels

include (jB_get_lang_dir().$lang_filename);

$dest_label = $label; // dest labels

// preload the source code, preg the hash key and use it as a key for the line 
$handle = fopen(jB_get_lang_dir()."english_default.php", "rb");
while ($buffer= fgets($handle, 4096)) {
	if (preg_match ('#\$label\[.([a-z0-9_]+).\].*#i', $buffer, $m)) {
		
		$source_code[$m[1]] = $buffer;
	}
}

JBPLUG_append_english_default_source($source_code); // append the english_default.php of all plugins
jb_theme_append_english_default_source($source_code); // // append the english_default.php of all themes



if ($_REQUEST['save']!='') {
	require_once ('../include/dynamic_forms.php');
	require_once ('../include/code_functions.php');
	require_once ('../include/category.inc.php');

	$sql = "SELECT * FROM form_fields WHERE `field_type`='RADIO' or `field_type`='CHECK' or `field_type`='MSELECT'  ";
	$result = JB_mysql_query($sql) or die (mysql_error().$sql);
	while ($row = mysql_fetch_array($result, MYSQL_ASSOC)) {
		JB_format_codes_translation_table ($row['field_id']);
	}

	// update forms
	// (copy English to new lang)

	JB_format_field_translation_table (1);
	JB_format_field_translation_table (2);
	JB_format_field_translation_table (3);

	// update email templates

	JB_format_email_translation_table();

	$out = "<?php\n";
	$out .= "///////////////////////////////////////////////////////////////////////////\n";
	$out .= "// IMPORTANT NOTICE\n";
	$out .= "///////////////////////////////////////////////////////////////////////////\n";
	$out .= "// This file was generated by a script!\n";
	$out .= "// (Admin->Translation tools)\n";
	$out .= "// Please do not edit the language files by hand\n";
	$out .= "// - please always use the Language Translation / Editing tool found\n";
	$out .= "// in Admin->Languages\n";
	$out .= "// To add a new phrase for the \$label, please edit english_default.php, and\n";
	$out .= "// then vist Admin->Main Summary where the language files will be\n";
	$out .= "// automatically merged with this file.\n";
	$out .= "///////////////////////////////////////////////////////////////////////////\n";


	foreach ($source_label as $key=>$val) {
		if (isset($_REQUEST[$key])) {

			
			$_REQUEST[$key] = str_replace ('\\"','"', $_REQUEST[$key] );
			$out .= "\$label['$key']='". $_REQUEST[$key]."';\n";
		} else {
			$out .= "\$label['$key']='". str_replace ("'", "\'", $label[$key] )."';\n"; // preserve the old label
		}
	}
	$out .= "?>\n";
	$handler = fopen (jB_get_lang_dir().$lang_filename, "w");
	fputs ($handler, $out);
	// load the new labels
	include (jB_get_lang_dir().$lang_filename);
	$dest_label = $label; // dest labels

	touch (jb_get_config_dir().'config.php'); // update config.php timestamp.
}



?>

<h3>Jamit Job Board Language Translation tool.</h3>
<b>IMPORTANT:</b> Backup your language files before using this tool! This tool will overwrite any code in the target file with machine-generated code. Also, please wait until the page is fully loaded before saving.<br>
<?php

if (!is_writeable(jB_get_lang_dir().$lang_filename)) {
	$JBMarkup->error_msg("<b>Warning:</b></font> The file ".jB_get_lang_dir().jb_escape_html($lang_filename)." is not writable. You must give it write permissions for changes to take effect. You may set back to read-only permissions after saving changes.");
}

?>
<form method="POST" name="form1" action="translation_tool.php">


<div style="background-color: white; border: 2px solid #FF8000; padding:15px; margin:5px;">Caution: HTML tags are allowed in the input, eg. &lt;b&gt;example&lt;b&gt;<br>
For normal text, please use <b>HTML Entities</b><br>
- If you want to use a <B>&gt;</B> character, please type in <B>&amp;gt;</B> instead<br>
- To use a <B>&lt;</B> character, please type in <B>&amp;lt;</B> instead<br>
- For an <B>&amp;</B>, please use <B>&amp;amp;</B> instead<br>
- For <B>"</B>, please use <B>&amp;quot;</B><br>
</div>
<input type="hidden" name="target_lang" value="<?php echo jb_escape_html($_REQUEST['target_lang']); ?>" >

<table style="margin: 0 auto; background-color: #d9d9d9; width:100%; border:0px"  cellSpacing="2" cellPadding="3"  >
<tr bgColor="#eaeaea">
	<td ><b>Source: english_default.php (from lang/english_default.php and themes and plugins)</b></td><td ><b><font size="2">Target Language: <?php echo $lang_name;?> (<?php echo $lang_filename; ?>)</font></b><br><br></td>
</tr>


<?php


foreach ($source_label as $key => $val) {
	$i++;
	

	if ($bg_color == "#ffffff") {
		$bg_color = "#FFFFff";
	} else {
		$bg_color = "#ffffff";

	}

	?>
	
	
	<tr bgcolor="#E8E8E8">
	<td colspan="2"><small><b><?php echo $key; ?></b></small><br>
	
	<small><?php ob_start(); highlight_string("<?php ". ($source_code[$key])." ?>"); $buff = ob_get_contents(); $buff=str_replace('&nbsp;', ' ', $buff);  ob_end_clean(); echo $buff; ?></small>
	</td>

	</tr>


	<tr bgcolor="<?php echo $bg_color;?>">
		<td  width="50%" valign="top"><?php echo "<br><font size='2'>".htmlentities(str_replace('>', ">\n",$val))."</font><br>";  ?></td>
		<td valign="top" >
		<?php

		$label = htmlentities(stripslashes($dest_label[$key]));
		
		
	
		?>
		<textarea style="font-family: Arial; font-size: 10pt;" cols="60" rows="<?php $size = strlen ($val); $rows = round( $size / 40)+2; echo $rows; ?>"  name='<?php echo $key; ?>'><?php echo jb_escape_html($label);  ?></textarea></td>
	</tr>
	
	<?php
	if ($i > 5) {

		echo "<tr bgcolor='#BDD5E6'><td></td><td><input type='submit' name='save' value='Save'></td></tr>";
		$i=0;
	}
	?>

	<tr>
	<td colspan="2"><hr></td>
	</tr>

	<?php
	


}

?>
<tr bgcolor='#BDD5E6'><td></td><td><input type='submit' name='save' value='Save'></td></tr>
</table>
<?php

JB_admin_footer();
?>